apiVersion: v1
kind: Service
metadata:
  labels:
    app: movies
  name: movies
  namespace: movies
spec:
  ports:
  - port: 80 
    protocol: TCP
    targetPort: 80 
    nodePort: 30334
  selector:
    app: movies
  type: NodePort
